### ISSUE TITLE
'>' not supported between instances of 'NoneType' and 'tuple'

### ISSUE THREAD

**Issue by ying-hao** [acl-org/aclpubcheck#23]
I got this error when I check my paper. Can you kindly advise what I should do?

Full error:
Checking paper.pdf
Traceback (most recent call last):
  File "aclpubcheck-main/aclpubcheck/formatchecker.py", line 462, in <module>
    main()
  File "aclpubcheck-main/aclpubcheck/formatchecker.py", line 459, in main
    worker(submission, args.paper_type)
  File "aclpubcheck-main/aclpubcheck/formatchecker.py", line 424, in worker
    return Formatter().format_check(submission=pdf_path, paper_type=paper_type)
  File "aclpubcheck-main/aclpubcheck/formatchecker.py", line 77, in format_check
    self.check_page_num(paper_type)
  File "aclpubcheck-main/aclpubcheck/formatchecker.py", line 336, in check_page_num
    if marker > (page_threshold + 1, 1):
TypeError: '>' not supported between instances of 'NoneType' and 'tuple'

**Comment by crux82** [comment]
Can you share with me the problematic PDF in a private message?

**Comment by crux82** [comment]
After a quick look at the code, I think that you may have one or more pages without texts. 
Is it possible?

**Comment by ying-hao** [comment]
This error was gone when I reconvert the file. I guess something was wrong during the conversion. Thanks!
