### ISSUE TITLE
"attempt to perform an operation not allowed" exception

### ISSUE THREAD

**Issue by efatmae** [acl-org/aclpubcheck#24]
Hi, I got the following error. Can you help with that?

Checking ./SRW.pdf
Traceback (most recent call last):
  File "aclpubcheck/formatchecker.py", line 462, in <module>
    main()
  File "aclpubcheck/formatchecker.py", line 459, in main
    worker(submission, args.paper_type)
  File "aclpubcheck/formatchecker.py", line 424, in worker
    return Formatter().format_check(submission=pdf_path, paper_type=paper_type)
  File "aclpubcheck/formatchecker.py", line 76, in format_check
    self.check_page_margin(output_dir)
  File "aclpubcheck/formatchecker.py", line 275, in check_page_margin
    im = self.pdf.pages[page].to_image(resolution=150)
  File "/home/fatma/.local/lib/python3.8/site-packages/pdfplumber/page.py", line 296, in to_image
    return PageImage(self, **kwargs)
  File "/home/fatma/.local/lib/python3.8/site-packages/pdfplumber/display.py", line 54, in __init__
    self.original = get_page_image(
  File "/home/fatma/.local/lib/python3.8/site-packages/pdfplumber/display.py", line 40, in get_page_image
    with wand.image.Image(resolution=resolution, **spec) as img_init:
  File "/home/fatma/.local/lib/python3.8/site-packages/wand/image.py", line 9144, in __init__
    self.read(filename=filename)
  File "/home/fatma/.local/lib/python3.8/site-packages/wand/image.py", line 9815, in read
    self.raise_exception()
  File "/home/fatma/.local/lib/python3.8/site-packages/wand/resource.py", line 222, in raise_exception
    raise e
wand.exceptions.PolicyError: attempt to perform an operation not allowed by the security policy `PDF' @ error/constitute.c/IsCoderAuthorized/408

**Comment by crux82** [comment]
@efatmae did It work?

**Comment by efatmae** [comment]
The Colab version worked. I could not get it t work locally.
