### ISSUE TITLE
ModuleNotFoundError: No module named 'rebiber'

### ISSUE THREAD

**Issue by ZhangzihanGit** [acl-org/aclpubcheck#28]
Hi,

When using the provided Google Colab to run the check, it raised the below error:

```
Traceback (most recent call last):
  File "aclpubcheck-main/aclpubcheck/formatchecker.py", line 17, in <module>
    from name_check import PDFNameCheck
  File "/content/aclpubcheck-main/aclpubcheck/name_check.py", line 2, in <module>
    import rebiber
ModuleNotFoundError: No module named 'rebiber'
```

The library `rebiber` is missing.

Thanks.

**Comment by ZhangzihanGit** [comment]
After I installed `rebiber ` manually, another library is missing as well:

```
Traceback (most recent call last):
  File "aclpubcheck-main/aclpubcheck/formatchecker.py", line 17, in <module>
    from name_check import PDFNameCheck
  File "/content/aclpubcheck-main/aclpubcheck/name_check.py", line 3, in <module>
    from pylatexenc.latex2text import LatexNodes2Text
ModuleNotFoundError: No module named 'pylatexenc'
```

Is something wrong with recent commits? I can run the script without errors a few days ago.

**Comment by pranav-ust** [comment]
Ah, we added some new functions. Can you rerun the pip installs?

**Comment by pranav-ust** [comment]
Ah my bad, I forgot to push changes in the `setup.py`. I will fix this asap.
