### ISSUE TITLE
how to specify xxx.bib?

### ISSUE THREAD

**Issue by zh794390558** [acl-org/aclpubcheck#33]
```
B000000345144A:aclpubcheck$ python3 aclpubcheck/formatchecker.py --paper_type short ~/Downloads/paddlespeech.pdf 
Checking /Users//Downloads/paddlespeech.pdf
sh: temp/before-rebiber-/Users/zhanghui41/Downloads/paddlespeech.bib: No such file or directory
Traceback (most recent call last):
  File "/Users//workspace/aclpubcheck/aclpubcheck/formatchecker.py", line 491, in <module>
    main()
  File "/Users//workspace/aclpubcheck/aclpubcheck/formatchecker.py", line 488, in main
    worker(submission, args.paper_type)
  File "/Users//workspace/aclpubcheck/aclpubcheck/formatchecker.py", line 452, in worker
    return Formatter().format_check(submission=pdf_path, paper_type=paper_type)
  File "/Users//workspace/aclpubcheck/aclpubcheck/formatchecker.py", line 83, in format_check
    self.check_references()
  File "/Users//workspace/aclpubcheck/aclpubcheck/formatchecker.py", line 429, in check_references
    output_strings = self.pdf_namecheck.execute(config)
  File "/Users//workspace/aclpubcheck/aclpubcheck/name_check.py", line 239, in execute
    self.apply_rebiber()
  File "/Users//workspace/aclpubcheck/aclpubcheck/name_check.py", line 49, in apply_rebiber
    all_bib_entries = rebiber.load_bib_file(f'temp/before-rebiber-{self.filename}.bib')
  File "/usr/local/lib/python3.9/site-packages/rebiber/bib2json.py", line 20, in load_bib_file
    with open(bibpath, encoding='utf8') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'temp/before-rebiber-/Users//Downloads/paddlespeech.bib'

```

**Comment by crux82** [comment]
I think it can be solved by @pranav-ust

**Comment by pranav-ust** [comment]
It is getting confused with the path. For now, you can put the pdf in same directory and try again (like avoid `~/Downloads`). Meanwhile I will give a PR fix so it works for all paths.

**Comment by pranav-ust** [comment]
Issue solved in https://github.com/acl-org/aclpubcheck/pull/35. Please double check and close this issue.

**Comment by zh794390558** [comment]
`mkdir -p temp/before-rebiber` and ` temp/after-rebiber`, and put ref.bit into it  can work.
