### ISSUE TITLE
Security Error when running formatchecker

### ISSUE THREAD

**Issue by umgupta** [acl-org/aclpubcheck#8]
Hi, 
I am using Linux 20.04 with `python3.8`. I get the following security error when running `formatchecker.py`. The pdf file was generated using `pdflatex` on the same machine. 

```
Checking main.pdf
Traceback (most recent call last):
  File "aclpubcheck/formatchecker.py", line 357, in <module>
    main()
  File "aclpubcheck/formatchecker.py", line 354, in main
    worker(submission)
  File "aclpubcheck/formatchecker.py", line 319, in worker
    Formatter().format_check(submission=pdf_path, paper_type=args.paper_type)
  File "aclpubcheck/formatchecker.py", line 63, in format_check
    self.check_page_margin()
  File "aclpubcheck/formatchecker.py", line 171, in check_page_margin
    im = self.pdf.pages[page].to_image(resolution=150)
  File "/home/umang/.local/lib/python3.8/site-packages/pdfplumber/page.py", line 296, in to_image
    return PageImage(self, **kwargs)
  File "/home/umang/.local/lib/python3.8/site-packages/pdfplumber/display.py", line 54, in __init__
    self.original = get_page_image(
  File "/home/umang/.local/lib/python3.8/site-packages/pdfplumber/display.py", line 40, in get_page_image
    with wand.image.Image(resolution=resolution, **spec) as img_init:
  File "/home/umang/.local/lib/python3.8/site-packages/wand/image.py", line 9144, in __init__
    self.read(filename=filename)
  File "/home/umang/.local/lib/python3.8/site-packages/wand/image.py", line 9815, in read
    self.raise_exception()
  File "/home/umang/.local/lib/python3.8/site-packages/wand/resource.py", line 222, in raise_exception
    raise e
wand.exceptions.PolicyError: attempt to perform an operation not allowed by the security policy `PDF' @ error/constitute.c/IsCoderAuthorized/408

```

Is there a workaround for this that I have missed?

**Comment by ryancotterell** [comment]
Can you take a look here https://stackoverflow.com/questions/52998331/imagemagick-security-policy-pdf-blocking-conversion? This seems to be fixable.

**Comment by ryancotterell** [comment]
You can also use the CodaLab version if you can't run the software locally. See https://colab.research.google.com/drive/1Sq6ilmrFUQpUFMkV71U8-Wf0madW-Uer?usp=sharing.

**Comment by umgupta** [comment]
> Can you take a look here https://stackoverflow.com/questions/52998331/imagemagick-security-policy-pdf-blocking-conversion? This seems to be fixable.

Yup, this worked. Thanks!
